apiVersion: v1
kind: Service
metadata:
  name: parking-manager-service
spec:
  type: LoadBalancer
  loadBalancerIP: "34.73.25.235"
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: parking-manager